### ISSUE TITLE
Add fluid-icon to icon download list

### ISSUE THREAD

**Issue by simon-ostergren** [RandomDevs/browser-home#22]
For example:
`<link rel="fluid-icon" href="https://github.com/fluidicon.png" title="GitHub">`

**Comment by simon-ostergren** [comment]
Maybe weird format, @andreasgoth what do you think?
<img width="236" alt="bild" src="https://user-images.githubusercontent.com/4416879/69889360-c1237980-12f0-11ea-9de8-dff68bf46a35.png">

**Comment by andreasgoth** [comment]
I'm guessing not particularly common either. But couldn't hurt if there is nothing else available, no?

**Comment by andreasgoth** [comment]
Added in 72fe6055c8d31df9967294ac6fe529ca8af741f5
